import { StyleSheet } from 'react-native';
import { scale, verticalScale } from 'utils';
export default function ({ COLORS }) {
    return StyleSheet.create({
        RowItem: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            width: '100%',
        },
        RowItemCenter: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            width: '100%',
        },
        RowItemEnd: {
            flexDirection: 'row',
            justifyContent: 'flex-end',
            alignItems: 'center',
            width: '100%',
        },
        RowItemStart: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
            width: '100%',
        },
        ColRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
        },
        ColRowCenter: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
        },
        ColRowStart: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
        },
        ColRowEnd: {
            flexDirection: 'row',
            justifyContent: 'flex-end',
            alignItems: 'center',
        },
        ColCenter: {
            alignItems: 'center',
        },
        flexRow: {
            flexDirection: 'row',
        },
        image0: {
            width: scale(390),
            height: scale(302),
        },
        TxtSectionSignUp1: {
            marginBottom: verticalScale(12),
            fontSize: verticalScale(22),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        TxtSectionSignUp2: {
            marginBottom: verticalScale(15),
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            lineHeight: 24,
            color: COLORS.Color726,
        },
        TextsInput4: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 20,
            color: COLORS.Color280,
        },
        InputRect5: {
            paddingRight: scale(200),
            paddingLeft: scale(14),
            borderWidth: 1,
            borderColor: COLORS.Color321,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Input3: {
            marginBottom: verticalScale(16),
            width: '100%',
            height: verticalScale(48),
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        TextsInput7: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 20,
            color: COLORS.Color280,
        },
        InputRect8: {
            paddingRight: scale(234),
            paddingLeft: scale(14),
            borderWidth: 1,
            borderColor: COLORS.Color321,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Input6: {
            marginBottom: verticalScale(64),
            width: '100%',
            height: verticalScale(48),
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        TextsButton11: {
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            color: COLORS.Color672,
        },
        ButtonRect10: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(13),
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button9: {
            marginBottom: verticalScale(29),
            width: '100%',
            height: verticalScale(52),
        },
        RowItemSectionSignUp12: {
            marginBottom: verticalScale(26),
        },
        LineSectionSignUp13: {
            borderColor: COLORS.Color206,
            width: '100%',
            borderBottomWidth: 1,
        },
        TxtSectionSignUp14: {
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(13),
            fontFamily: 'Muli',
            lineHeight: 15,
            color: COLORS.Color726,
        },
        LineSectionSignUp15: {
            borderColor: COLORS.Color206,
            width: '100%',
            borderBottomWidth: 1,
        },
        ButtonRect17: {
            backgroundColor: COLORS.Color148,
            display: 'flex',
            alignItems: 'center',
            flexDirection: 'row',
            textAlign: 'center',
            justifyContent: 'space-between',
            borderTopLeftRadius: 60,
            borderTopRightRadius: 60,
            borderBottomRightRadius: 60,
            borderBottomLeftRadius: 60,
        },
        Button16: {
            width: scale(38),
            height: verticalScale(38),
        },
        ButtonRect19: {
            backgroundColor: COLORS.Color148,
            display: 'flex',
            alignItems: 'center',
            flexDirection: 'row',
            textAlign: 'center',
            justifyContent: 'space-between',
            borderTopLeftRadius: 60,
            borderTopRightRadius: 60,
            borderBottomRightRadius: 60,
            borderBottomLeftRadius: 60,
        },
        Button18: {
            width: scale(38),
            height: verticalScale(38),
        },
        ButtonRect21: {
            backgroundColor: COLORS.Color148,
            display: 'flex',
            alignItems: 'center',
            flexDirection: 'row',
            textAlign: 'center',
            justifyContent: 'space-between',
            borderTopLeftRadius: 60,
            borderTopRightRadius: 60,
            borderBottomRightRadius: 60,
            borderBottomLeftRadius: 60,
        },
        Button20: {
            width: scale(38),
            height: verticalScale(38),
        },
        EleSectionSignUp22: {
            marginBottom: verticalScale(19),
        },
        ParagraphSectionSignUp23: {
            marginBottom: verticalScale(34),
            flexDirection: 'row',
        },
        TxtSectionSignUp24: {
            fontSize: verticalScale(14),
            fontFamily: 'Muli',
            lineHeight: 15,
            color: COLORS.Color525,
        },
        image25: {
            width: scale(390),
            height: scale(302),
        },
        TxtSectionSignIn26: {
            marginBottom: verticalScale(12),
            fontSize: verticalScale(22),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        TxtSectionSignIn27: {
            marginBottom: verticalScale(15),
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            lineHeight: 24,
            color: COLORS.Color726,
        },
        TextsInput29: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 20,
            color: COLORS.Color280,
        },
        InputRect30: {
            paddingRight: scale(200),
            paddingLeft: scale(14),
            borderWidth: 1,
            borderColor: COLORS.Color321,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Input28: {
            marginBottom: verticalScale(16),
            width: '100%',
            height: verticalScale(48),
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        TextsInput32: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 20,
            color: COLORS.Color280,
        },
        InputRect33: {
            paddingRight: scale(234),
            paddingLeft: scale(14),
            borderWidth: 1,
            borderColor: COLORS.Color321,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Input31: {
            marginBottom: verticalScale(18),
            width: '100%',
            height: verticalScale(48),
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        TxtSectionSignIn34: {
            marginBottom: verticalScale(24),
            fontSize: verticalScale(15),
            fontFamily: 'Muli',
            lineHeight: 16,
            color: COLORS.Color525,
        },
        TextsButton37: {
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            color: COLORS.Color672,
        },
        ButtonRect36: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(13),
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button35: {
            marginBottom: verticalScale(29),
            width: '100%',
            height: verticalScale(52),
        },
        RowItemSectionSignIn38: {
            marginBottom: verticalScale(26),
        },
        LineSectionSignIn39: {
            borderColor: COLORS.Color206,
            width: '100%',
            borderBottomWidth: 1,
        },
        TxtSectionSignIn40: {
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(13),
            fontFamily: 'Muli',
            lineHeight: 15,
            color: COLORS.Color726,
        },
        LineSectionSignIn41: {
            borderColor: COLORS.Color206,
            width: '100%',
            borderBottomWidth: 1,
        },
        EleSectionSignIn42: {
            marginBottom: verticalScale(19),
        },
        ParagraphSectionSignIn43: {
            marginBottom: verticalScale(34),
            flexDirection: 'row',
        },
        TxtSectionSignIn44: {
            fontSize: verticalScale(14),
            fontFamily: 'Muli',
            lineHeight: 15,
            color: COLORS.Color525,
        },
        image45: {
            marginBottom: verticalScale(32),
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            width: scale(390),
            height: scale(530),
        },
        TxtSectionForgetPass46: {
            marginBottom: verticalScale(16),
            fontSize: verticalScale(22),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        TextsInput48: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color758,
        },
        InputRect49: {
            paddingRight: scale(161),
            paddingLeft: scale(12),
            borderWidth: 1,
            borderColor: COLORS.Color321,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Input47: {
            marginBottom: verticalScale(16),
            width: '100%',
            height: verticalScale(48),
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        TextsButton52: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color672,
        },
        ButtonRect51: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(13),
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button50: {
            marginBottom: verticalScale(23),
            width: '100%',
            height: verticalScale(51),
        },
        TxtSectionForgetPass53: {
            marginBottom: verticalScale(31),
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(14),
            fontFamily: 'Muli',
            lineHeight: 15,
            color: COLORS.Color525,
        },
        SectionPaddingquestion255: {
            paddingBottom: verticalScale(-2),
            paddingTop: verticalScale(-6),
            paddingRight: scale(120),
            paddingLeft: scale(120),
        },
        Txtquestion256: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        Image57: {
            width: scale(390),
            height: scale(84),
        },
        SectionPaddingquestion258: {
            paddingBottom: verticalScale(32),
            paddingTop: verticalScale(32),
            paddingRight: scale(32),
            paddingLeft: scale(32),
        },
        Txtquestion259: {
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 39,
            color: COLORS.Color209,
        },
        Txtquestion260: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        TextsCheckBox62: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox61: {
            flexDirection: 'row',
        },
        TextsCheckBox64: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox63: {
            flexDirection: 'row',
        },
        TextsCheckBox66: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox65: {
            flexDirection: 'row',
        },
        TextsCheckBox68: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox67: {
            flexDirection: 'row',
        },
        TextsCheckBox70: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox69: {
            flexDirection: 'row',
        },
        TextsCheckBox72: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox71: {
            flexDirection: 'row',
        },
        TextsCheckBox74: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox73: {
            flexDirection: 'row',
        },
        TextsCheckBox76: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox75: {
            flexDirection: 'row',
        },
        TextsCheckBox78: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color603,
        },
        CheckBox77: {
            flexDirection: 'row',
        },
        TextsButton81: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color963,
        },
        ButtonRect80: {
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
            alignSelf: 'center',
        },
        Button79: {
            width: '90%',
            height: verticalScale(52),
            alignSelf: 'center',
        },
        image82: {
            marginBottom: verticalScale(32),
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            width: scale(326),
            height: scale(417),
        },
        TxtSectionVerification83: {
            marginBottom: verticalScale(8),
            fontSize: verticalScale(22),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        TxtSectionVerification84: {
            marginBottom: verticalScale(14),
            fontSize: verticalScale(15),
            fontFamily: 'Muli',
            lineHeight: 16,
            color: COLORS.Color726,
        },
        InputRect86: {
            borderWidth: 1,
            borderColor: COLORS.Color321,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Input85: {
            marginBottom: verticalScale(10),
            width: '100%',
            height: verticalScale(48),
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        TxtSectionVerification87: {
            marginBottom: verticalScale(39),
            fontSize: verticalScale(15),
            fontFamily: 'Muli',
            lineHeight: 16,
            color: COLORS.Color525,
        },
        TextsButton90: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color672,
        },
        ButtonRect89: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(13),
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button88: {
            marginBottom: verticalScale(21),
            width: '100%',
            height: verticalScale(51),
        },
        TextsButton93: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color289,
        },
        ButtonRect92: {
            paddingBottom: verticalScale(11),
            paddingTop: verticalScale(10),
            paddingRight: 0,
            paddingLeft: 0,
            borderWidth: 2,
            borderColor: COLORS.Color289,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button91: {
            width: '100%',
            height: verticalScale(51),
        },
        image94: {
            marginBottom: verticalScale(78),
            width: scale(390),
            height: scale(494),
        },
        TxtSectionQuestion95: {
            marginBottom: verticalScale(16),
            fontSize: verticalScale(22),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        TxtSectionQuestion96: {
            marginBottom: verticalScale(19),
            fontSize: verticalScale(14),
            fontFamily: 'Muli',
            lineHeight: 26,
            color: COLORS.Color726,
        },
        TextsButton99: {
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color672,
        },
        ButtonRect98: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(13),
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button97: {
            width: '100%',
            height: verticalScale(51),
        },
        EleHiquestion2100: {
            marginBottom: verticalScale(32),
        },
        TxtSectionTop101: {
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            // lineHeight: 42,
            color: COLORS.Color209,
        },
        Image102: {
            marginBottom: verticalScale(36),
            width: scale(381),
            height: scale(82),
        },
        SectionPaddingquestion6103: {
            paddingBottom: verticalScale(0),
            paddingTop: verticalScale(0),
            paddingRight: scale(32),
            paddingLeft: scale(32),
            marginBottom: verticalScale(178),
        },
        Txtquestion6104: {
            marginBottom: verticalScale(36),
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 39,
            color: COLORS.Color209,
        },
        Txtquestion6105: {
            marginBottom: verticalScale(16),
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 39,
            color: COLORS.Color209,
        },
        TextsInput107: {
            fontSize: verticalScale(14),
            fontFamily: 'Muli',
            lineHeight: 36,
            color: COLORS.Color267,
        },
        InputRect108: {
            paddingRight: scale(160),
            paddingLeft: scale(15),
            borderWidth: 1,
            borderColor: COLORS.Color321,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Input106: {
            marginBottom: verticalScale(88),
            width: '100%',
            height: verticalScale(48),
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Txtquestion6109: {
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            lineHeight: 30,
            color: COLORS.Color209,
        },
        TextsButton112: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color672,
        },
        ButtonRect111: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(13),
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button110: {
            width: scale(146),
            height: verticalScale(51),
        },
        TextsButton115: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color209,
        },
        ButtonRect114: {
            paddingBottom: verticalScale(12),
            paddingTop: verticalScale(11),
            paddingRight: 0,
            paddingLeft: 0,
            borderWidth: 1,
            borderColor: COLORS.Color276,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 8,
            borderTopRightRadius: 8,
            borderBottomRightRadius: 8,
            borderBottomLeftRadius: 8,
        },
        ButtonRect1142: {
            paddingBottom: verticalScale(12),
            paddingTop: verticalScale(11),
            paddingRight: 0,
            paddingLeft: 0,
            backgroundColor: 'rgba(255,255,255,0.1607843137254902 )',
            shadowColor: 'rgba(255,255,255,0.1607843137254902 )',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 8,
            borderTopRightRadius: 8,
            borderBottomRightRadius: 8,
            borderBottomLeftRadius: 8,
        },
        Button113: {
            width: scale(148),
            height: verticalScale(51),
        },
        SectionPaddingquestion7117: {
            paddingBottom: verticalScale(-2),
            paddingTop: verticalScale(-6),
            justifyContent: 'center',
            alignItems: 'center',
        },
        Txtquestion7118: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        Image119: {
            width: scale(390),
            height: scale(84),
        },
        SectionPaddingquestion7120: {
            paddingBottom: verticalScale(0),
            paddingTop: verticalScale(0),
            paddingRight: scale(32),
            paddingLeft: scale(32),
        },
        Txtquestion7121: {
            marginBottom: verticalScale(46),
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 39,
            color: COLORS.Color209,
        },
        SectionPaddingquestion7122: {
            marginBottom: verticalScale(24),
        },
        Txtquestion7123: {
            marginBottom: verticalScale(16),
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 39,
            color: COLORS.Color209,
        },
        TextsInput125: {
            fontSize: verticalScale(14),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color267,
        },
        InputRect126: {
            paddingRight: scale(166),
            paddingLeft: scale(15),
            borderWidth: 1,
            borderColor: COLORS.Color321,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Input124: {
            width: '100%',
            height: verticalScale(48),
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Txtquestion7127: {
            marginBottom: verticalScale(25),
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 39,
            color: COLORS.Color209,
        },
        TextsCheckBox129: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox128: {
            paddingBottom: verticalScale(13),
            paddingTop: verticalScale(11),
            paddingRight: scale(232),
            paddingLeft: scale(16),
            marginBottom: verticalScale(16),
            flexDirection: 'row',
        },
        TextsCheckBox131: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox130: {
            paddingBottom: verticalScale(13),
            paddingTop: verticalScale(11),
            paddingRight: scale(219),
            paddingLeft: scale(16),
            marginBottom: verticalScale(16),
            flexDirection: 'row',
        },
        TextsCheckBox133: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox132: {
            paddingBottom: verticalScale(13),
            paddingTop: verticalScale(11),
            paddingRight: scale(216),
            paddingLeft: scale(16),
            flexDirection: 'row',
        },
        image134: {
            marginBottom: verticalScale(22),
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            width: scale(390),
            height: scale(452.02),
        },
        TxtSectionVerify135: {
            marginBottom: verticalScale(16),
            fontSize: verticalScale(22),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        TextsButton138: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color672,
        },
        ButtonRect137: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(13),
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button136: {
            marginBottom: verticalScale(24),
            width: '100%',
            height: verticalScale(51),
        },
        TxtSectionVerify139: {
            marginBottom: verticalScale(26),
            fontSize: verticalScale(14),
            fontFamily: 'Muli',
            lineHeight: 26,
            color: COLORS.Color516,
        },
        SectionPaddingSectiontop1140: {
            paddingBottom: verticalScale(-2),
            paddingTop: verticalScale(-6),
            justifyContent: 'center',
            alignItems: 'center',
        },
        TxtSectiontop1141: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        image142: {
            marginBottom: verticalScale(49),
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            width: scale(390),
            height: scale(452.02),
        },
        TxtSectionStart143: {
            marginBottom: verticalScale(16),
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(26),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 24,
            color: COLORS.Color726,
        },
        TxtSectionStart144: {
            marginBottom: verticalScale(83),
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(15),
            fontFamily: 'Muli',
            lineHeight: 26,
            color: COLORS.Color726,
        },
        TextsButton147: {
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color672,
        },
        ButtonRect146: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(13),
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button145: {
            width: '100%',
            height: verticalScale(51),
        },
        EleGettingstarted3148: {
            marginBottom: verticalScale(32),
        },
        image320: {
            marginTop: verticalScale(103),
            marginBottom: verticalScale(103),
            width: '100%',
            height: scale(175),
        },
        image221: {
            width: scale(390),
            // height: scale(144),
        },
        image1190: {
            marginBottom: verticalScale(103),
            width: scale(390),
            height: scale(130),
        },
        imagelogo0: {
            marginTop: verticalScale(16),
            marginBottom: verticalScale(64),
            width: '100%',
            height: scale(52),
        },
        imagevector1: {
            marginBottom: verticalScale(5),
            width: '100%',
            height: scale(232),
        },
        imagevector2: {
            marginTop: '95%',
            width: '100%',
            height: scale(450),
            alignSelf: 'center',
            position: 'absolute',
        },
        SectionPaddingintro62: {
            paddingBottom: verticalScale(32),
            paddingTop: verticalScale(0),
            width: '100%',
        },
        Txtintro63: {
            // marginBottom: verticalScale(42),
            marginTop: verticalScale(100),
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(20),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            paddingRight: scale(32),
            paddingLeft: scale(32),
            lineHeight: 42,
            color: COLORS.white,
        },
        buttonRect5: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(14),
            paddingRight: 0,
            paddingLeft: 0,
            backgroundColor: COLORS.Color611,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            elevation: 5,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        button4: {
            marginBottom: verticalScale(28),
            marginTop: verticalScale(60),
            width: scale(314),
            height: verticalScale(52),
            alignSelf: 'center',
        },
        Textsbutton6: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color378,
        },
        TxtSectionTop0111: {
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            flexWrap: 'wrap',
            // lineHeight: 42,
            color: COLORS.Color571,
        },
        EleNotification122: {
            marginBottom: verticalScale(40),
        },
        EleNotification128: {
            marginBottom: verticalScale(32),
        },
        SectionPaddingNotification123: {
            paddingBottom: verticalScale(0),
            paddingTop: verticalScale(0),
            paddingRight: scale(32),
            paddingLeft: scale(32),
            marginBottom: verticalScale(266),
        },
        RowItemSectionEvent24: {
            marginBottom: verticalScale(16),
        },
        TxtSectionEvent25: {
            fontSize: verticalScale(15),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 24,
            color: COLORS.Color786,
        },
        EleChat218: {
            marginBottom: verticalScale(32),
        },
        imageprogram15: {
            borderWidth: 1,
            borderColor: COLORS.Color182,
            shadowColor: 'rgba(0,0,0,0.04)',
            shadowOffset: { width: 0, height: 3 },
            shadowRadius: 16,
            width: scale(57),
            height: scale(57),
            borderTopLeftRadius: 10,
            borderTopRightRadius: 10,
            borderBottomRightRadius: 10,
            borderBottomLeftRadius: 10,
        },
        TxtSectionProgram16: {
            fontSize: verticalScale(15),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 24,
            color: COLORS.Color786,
        },
        TxtSectionProgram17: {
            fontSize: verticalScale(14),
            fontFamily: 'Muli',
            lineHeight: 24,
            color: COLORS.Color745,
        },
        EleSearch4: {
            marginBottom: verticalScale(30),
        },
        SectionPaddingSearch5: {
            paddingBottom: verticalScale(0),
            paddingTop: verticalScale(0),
            paddingRight: scale(32),
            paddingLeft: scale(32),
            marginBottom: verticalScale(410),
        },
        RowItemSearch6: {
            marginBottom: verticalScale(34),
        },
        InputRect9: {
            // paddingRight: scale(145),
            paddingLeft: scale(23),
            backgroundColor: COLORS.white,
            shadowColor: 'rgba(140,140,140,0.06)',
            shadowOffset: { width: 0, height: 15 },
            shadowRadius: 29,
            elevation: 5,
            // opacity: 0.78,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Input7: {
            width: '100%',
            height: verticalScale(51),
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        TextsInput8: {
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color519,
        },
        Button10: {
            width: scale(52),
            height: verticalScale(51),
        },
        ButtonRect11: {
            paddingBottom: verticalScale(15),
            paddingTop: verticalScale(16),
            paddingRight: scale(17),
            paddingLeft: scale(17),
            backgroundColor: COLORS.white,
            shadowColor: 'rgba(140,140,140,0.06)',
            shadowOffset: { width: 0, height: 15 },
            shadowRadius: 29,
            // opacity: 0.78,
            elevation: 2,
            display: 'flex',
            alignItems: 'center',
            flexDirection: 'row',
            textAlign: 'center',
            justifyContent: 'space-between',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        SectionPaddingSearch12: {
            paddingBottom: verticalScale(16),
            paddingTop: verticalScale(16),
            // paddingRight: scale(16),
            // paddingLeft: scale(16),
            marginBottom: verticalScale(16),
        },
        image14: {
            borderWidth: 1,
            borderColor: COLORS.Color364,
            width: scale(59),
            height: scale(69),
            borderTopLeftRadius: 10,
            borderTopRightRadius: 10,
            borderBottomRightRadius: 10,
            borderBottomLeftRadius: 10,
            backgroundColor: 'red',
        },
        TxtSearch15: {
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 22,
            color: COLORS.Color786,
        },
        TxtSearch16: {
            fontSize: verticalScale(12),
            fontFamily: 'Muli',
            lineHeight: 18,
            color: COLORS.Color786,
        },
        TxtSearch17: {
            alignSelf: 'flex-end',
            textAlign: 'right',
            fontSize: verticalScale(13),
            fontFamily: 'Muli',
            lineHeight: 20,
            color: COLORS.Color786,
        },
        SectionEvent: {
            paddingBottom: verticalScale(18),
            paddingTop: verticalScale(11),
            paddingRight: scale(16),
            paddingLeft: scale(17),
            backgroundColor: COLORS.Color611,
            shadowColor: 'rgba(140,140,140,0.06)',
            shadowOffset: { width: 0, height: 15 },
            shadowRadius: 29,
            // opacity: 0.78,
            elevation: 2,
            width: '100%',
            alignItems: 'center',
            // height: verticalScale(144),
            borderTopLeftRadius: 21,
            borderTopRightRadius: 21,
            borderBottomRightRadius: 21,
            borderBottomLeftRadius: 21,
        },
        EleChat330: {
            marginBottom: verticalScale(44),
        },
        ButtonRect26: {
            backgroundColor: COLORS.white,
            display: 'flex',
            alignItems: 'center',
            flexDirection: 'row',
            textAlign: 'center',
            justifyContent: 'space-between',
        },
        Button25: {
            width: scale(34),
            height: verticalScale(34),
        },
        TxtSectionTopchat27: {
            fontSize: verticalScale(15),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 24,
            color: COLORS.Color726,
            alignSelf: 'center',
        },
        TxtSectionTopchat28: {
            fontSize: verticalScale(11),
            fontFamily: 'Muli',
            lineHeight: 24,
            color: COLORS.Color745,
            alignSelf: 'center',
        },
        image29: {
            width: scale(37),
            height: scale(37),
            alignSelf: 'center',
            borderTopLeftRadius: 10,
            borderTopRightRadius: 10,
            borderBottomRightRadius: 10,
            borderBottomLeftRadius: 10,
        },
        SectionPaddingChat331: {
            paddingBottom: verticalScale(32),
            paddingTop: verticalScale(0),
            paddingRight: scale(32),
            paddingLeft: scale(32),
        },
        SectionPaddingChat332: {
            marginBottom: verticalScale(16),
        },
        EleChat334: {
            marginBottom: verticalScale(8),
        },
        TxtChat335: {
            fontSize: verticalScale(13),
            fontFamily: 'Muli',
            color: COLORS.Color522,
        },
        ectionPaddingChat336: {
            marginBottom: verticalScale(16),
        },
        EleChat337: {
            marginBottom: verticalScale(8),
        },
        TxtChat338: {
            fontSize: verticalScale(13),
            fontFamily: 'Muli',
            color: COLORS.Color522,
        },
        InputRect48: {
            paddingRight: scale(10),
            paddingLeft: scale(14),
            borderWidth: 1,
            borderColor: COLORS.Color375,
            backgroundColor: COLORS.white,
            shadowColor: 'rgba(140,140,140,0.06)',
            shadowOffset: { width: 0, height: 15 },
            shadowRadius: 29,
            elevation: 2,
            borderTopLeftRadius: 8,
            borderTopRightRadius: 8,
            borderBottomRightRadius: 8,
            borderBottomLeftRadius: 8,
        },
        Input46: {
            width: '97%',
            alignSelf: 'flex-end',
            height: verticalScale(48),
            borderTopLeftRadius: 8,
            borderTopRightRadius: 8,
            borderBottomRightRadius: 8,
            borderBottomLeftRadius: 8,
            paddingRight: scale(10),
            paddingLeft: scale(14),
            borderWidth: 1,
            borderColor: COLORS.Color375,
            backgroundColor: COLORS.white,
            shadowColor: 'rgba(140,140,140,0.06)',
            shadowOffset: { width: 0, height: 15 },
            shadowRadius: 29,
            elevation: 2,
        },
        TextsInput47: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color718,
        },
        ButtonRect50: {
            paddingBottom: verticalScale(16),
            paddingTop: verticalScale(16),
            paddingRight: scale(15),
            paddingLeft: scale(15),
            backgroundColor: COLORS.Color148,
            shadowColor: 'rgba(177,177,177,0.16)',
            shadowOffset: { width: 0, height: 1 },
            shadowRadius: 17,
            elevation: 2,
            display: 'flex',
            alignItems: 'center',
            flexDirection: 'row',
            textAlign: 'center',
            justifyContent: 'space-between',
            borderTopLeftRadius: 7,
            borderTopRightRadius: 7,
            borderBottomRightRadius: 7,
            borderBottomLeftRadius: 7,
        },
        Button49: {
            width: scale(48),
            // height: scale(30),
            alignSelf: 'center',
        },
        TxtSectionChat33: {
            fontSize: verticalScale(14),
            fontFamily: 'Muli',
            lineHeight: 24,
            color: COLORS.Color375,
        },
        EleHome265: {
            marginBottom: verticalScale(32),
        },
        image60: {
            width: scale(148),
            height: scale(44),
        },
        ButtonRect62: {
            paddingBottom: verticalScale(6),
            paddingTop: verticalScale(6),
            paddingRight: scale(7),
            paddingLeft: scale(10),
            backgroundColor: COLORS.white,
            display: 'flex',
            alignItems: 'center',
            flexDirection: 'row',
            textAlign: 'center',
            justifyContent: 'space-between',
        },
        Button61: {
            width: scale(35),
            height: verticalScale(33),
        },
        SectionPaddingHome266: {
            paddingBottom: verticalScale(0),
            paddingTop: verticalScale(0),
            paddingRight: scale(32),
            paddingLeft: scale(32),
            marginBottom: verticalScale(67),
        },
        TxtHome267: {
            marginBottom: verticalScale(23),
            fontSize: verticalScale(24),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 24,
            color: COLORS.Color786,
        },
        image68: {
            width: scale(312),
            height: scale(136),
            borderTopLeftRadius: 21,
            borderTopRightRadius: 21,
            borderBottomRightRadius: 0,
            borderBottomLeftRadius: 0,
        },
        TxtSectionhome70: {
            marginVertical: verticalScale(15),
            fontSize: verticalScale(19),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 24,
            color: COLORS.Color726,
        },
        RowItemSectionhome71: {
            marginBottom: verticalScale(14),
        },
        TxtSectionhome72: {
            fontSize: verticalScale(14),
            fontFamily: 'Muli',
            lineHeight: 24,
            color: COLORS.Color726,
        },
        TxtSectionhome73: {
            fontSize: verticalScale(15),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 24,
            color: COLORS.Color726,
        },
        TxtSectionhome732: {
            fontSize: verticalScale(15),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 24,
            color: COLORS.Color726,
            textAlign: 'right',
        },
        Button910: {
            width: scale(28.45),
            height: verticalScale(25.27),
        },
        ButtonRect920: {
            paddingBottom: verticalScale(1),
            paddingTop: verticalScale(1),
            paddingRight: scale(1),
            paddingLeft: scale(1),
            backgroundColor: COLORS.Color893,
            display: 'flex',
            alignItems: 'center',
            flexDirection: 'row',
            textAlign: 'center',
            justifyContent: 'space-between',
        },
        // EleMoreInfo24: {
        //     marginBottom: verticalScale(24),
        // },
        RowItemMoreInfo26: {
            marginBottom: verticalScale(28),
        },
        image7: {
            width: scale(137),
            height: scale(137),
            borderTopLeftRadius: 10,
            borderTopRightRadius: 10,
            borderBottomRightRadius: 10,
            borderBottomLeftRadius: 10,
        },
        ButtonRect9: {
            backgroundColor: COLORS.Color327,
            shadowColor: 'rgba(140,140,140,0.09)',
            shadowOffset: { width: 0, height: 3 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            flexDirection: 'row',
            textAlign: 'center',
            justifyContent: 'space-between',
            borderTopLeftRadius: 6,
            borderTopRightRadius: 6,
            borderBottomRightRadius: 6,
            borderBottomLeftRadius: 6,
        },
        Button8: {
            width: scale(40),
            height: scale(40),
            justifyContent: 'center',
            alignItems: 'center',
            marginTop: '150%',
        },
        TxtMoreInfo212: {
            marginBottom: verticalScale(16),
            marginTop: verticalScale(16),
            fontSize: verticalScale(19),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 24,
            color: COLORS.Color300,
        },
        TxtMoreInfo213: {
            marginBottom: verticalScale(16),
            fontSize: verticalScale(18),
            fontFamily: 'Muli',
            lineHeight: 29,
            color: COLORS.Color300,
        },
        TxtMoreInfo214: {
            marginBottom: verticalScale(41),
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            lineHeight: 29,
            color: COLORS.Color300,
        },
        SectionPaddingMoreInfo218: {
            paddingBottom: verticalScale(48),
            paddingTop: verticalScale(54),
            alignSelf: 'center',
            paddingRight: scale(32),
            paddingLeft: scale(32),
        },
        image19: {
            width: scale(326),
            height: scale(169),
            borderTopLeftRadius: 10,
            borderTopRightRadius: 10,
            borderBottomRightRadius: 10,
            borderBottomLeftRadius: 10,
        },
        SectionPaddingMoreInfo220: {
            paddingBottom: verticalScale(0),
            paddingTop: verticalScale(0),
            paddingRight: scale(32),
            paddingLeft: scale(32),
            marginBottom: verticalScale(32),
            alignSelf: 'center',
        },
        ButtonRect22: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(13),
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button21: {
            width: scale(326),
            height: verticalScale(51),
        },
        TextsButton23: {
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.white,
        },
        TxtSectionRow16: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 29,
            color: COLORS.Color300,
        },
        TxtSectionRow17: {
            alignSelf: 'flex-end',
            textAlign: 'right',
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 29,
            color: COLORS.Color300,
        },
        SectionPaddingMoreInfo25: {
            paddingBottom: verticalScale(0),
            paddingTop: verticalScale(0),
            paddingRight: scale(32),
            paddingLeft: scale(32),
        },
    });
}
