import { StyleSheet } from 'react-native';
import { scale, verticalScale } from 'utils';
export default function ({ COLORS }) {
    return StyleSheet.create({
        RowItem: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            width: '100%',
        },
        RowItemCenter: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            width: '100%',
        },
        RowItemEnd: {
            flexDirection: 'row',
            justifyContent: 'flex-end',
            alignItems: 'center',
            width: '100%',
        },
        RowItemStart: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
            width: '100%',
        },
        ColRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
        },
        ColRowCenter: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
        },
        ColRowStart: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
        },
        ColRowEnd: {
            flexDirection: 'row',
            justifyContent: 'flex-end',
            alignItems: 'center',
        },
        ColCenter: {
            alignItems: 'center',
        },
        flexRow: {
            flexDirection: 'row',
        },
        image0: {
            width: scale(390),
            height: scale(302),
        },
        TxtSectionSignUp1: {
            marginBottom: verticalScale(12),
            fontSize: verticalScale(22),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        TxtSectionSignUp2: {
            marginBottom: verticalScale(15),
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            lineHeight: 24,
            color: COLORS.Color726,
        },
        TextsInput4: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 20,
            color: COLORS.Color280,
        },
        InputRect5: {
            paddingRight: scale(200),
            paddingLeft: scale(14),
            borderWidth: 1,
            borderColor: COLORS.Color321,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Input3: {
            marginBottom: verticalScale(16),
            width: '100%',
            height: verticalScale(48),
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        TextsInput7: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 20,
            color: COLORS.Color280,
        },
        InputRect8: {
            paddingRight: scale(234),
            paddingLeft: scale(14),
            borderWidth: 1,
            borderColor: COLORS.Color321,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Input6: {
            marginBottom: verticalScale(64),
            width: '100%',
            height: verticalScale(48),
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        TextsButton11: {
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            color: COLORS.Color672,
        },
        ButtonRect10: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(13),
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button9: {
            marginBottom: verticalScale(29),
            width: '100%',
            height: verticalScale(52),
        },
        RowItemSectionSignUp12: {
            marginBottom: verticalScale(26),
        },
        LineSectionSignUp13: {
            borderColor: COLORS.Color206,
            width: '100%',
            borderBottomWidth: 1,
        },
        TxtSectionSignUp14: {
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(13),
            fontFamily: 'Muli',
            lineHeight: 15,
            color: COLORS.Color726,
        },
        LineSectionSignUp15: {
            borderColor: COLORS.Color206,
            width: '100%',
            borderBottomWidth: 1,
        },
        ButtonRect17: {
            backgroundColor: COLORS.Color148,
            display: 'flex',
            alignItems: 'center',
            flexDirection: 'row',
            textAlign: 'center',
            justifyContent: 'space-between',
            borderTopLeftRadius: 60,
            borderTopRightRadius: 60,
            borderBottomRightRadius: 60,
            borderBottomLeftRadius: 60,
        },
        Button16: {
            width: scale(38),
            height: verticalScale(38),
        },
        ButtonRect19: {
            backgroundColor: COLORS.Color148,
            display: 'flex',
            alignItems: 'center',
            flexDirection: 'row',
            textAlign: 'center',
            justifyContent: 'space-between',
            borderTopLeftRadius: 60,
            borderTopRightRadius: 60,
            borderBottomRightRadius: 60,
            borderBottomLeftRadius: 60,
        },
        Button18: {
            width: scale(38),
            height: verticalScale(38),
        },
        ButtonRect21: {
            backgroundColor: COLORS.Color148,
            display: 'flex',
            alignItems: 'center',
            flexDirection: 'row',
            textAlign: 'center',
            justifyContent: 'space-between',
            borderTopLeftRadius: 60,
            borderTopRightRadius: 60,
            borderBottomRightRadius: 60,
            borderBottomLeftRadius: 60,
        },
        Button20: {
            width: scale(38),
            height: verticalScale(38),
        },
        EleSectionSignUp22: {
            marginBottom: verticalScale(19),
        },
        ParagraphSectionSignUp23: {
            marginBottom: verticalScale(34),
            flexDirection: 'row',
        },
        TxtSectionSignUp24: {
            fontSize: verticalScale(14),
            fontFamily: 'Muli',
            lineHeight: 15,
            color: COLORS.Color718,
        },
        image25: {
            width: scale(390),
            height: scale(302),
        },
        TxtSectionSignIn26: {
            marginBottom: verticalScale(12),
            fontSize: verticalScale(22),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        TxtSectionSignIn27: {
            marginBottom: verticalScale(15),
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            lineHeight: 24,
            color: COLORS.Color726,
        },
        TextsInput29: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 20,
            color: COLORS.Color280,
        },
        InputRect30: {
            paddingRight: scale(200),
            paddingLeft: scale(14),
            borderWidth: 1,
            borderColor: COLORS.Color321,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Input28: {
            marginBottom: verticalScale(16),
            width: '100%',
            height: verticalScale(48),
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        TextsInput32: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 20,
            color: COLORS.Color280,
        },
        InputRect33: {
            paddingRight: scale(234),
            paddingLeft: scale(14),
            borderWidth: 1,
            borderColor: COLORS.Color321,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Input31: {
            marginBottom: verticalScale(18),
            width: '100%',
            height: verticalScale(48),
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        TxtSectionSignIn34: {
            marginBottom: verticalScale(24),
            fontSize: verticalScale(15),
            fontFamily: 'Muli',
            lineHeight: 16,
            color: COLORS.Color525,
        },
        TextsButton37: {
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            color: COLORS.Color672,
        },
        ButtonRect36: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(13),
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button35: {
            marginBottom: verticalScale(29),
            width: '100%',
            height: verticalScale(52),
        },
        RowItemSectionSignIn38: {
            marginBottom: verticalScale(26),
        },
        LineSectionSignIn39: {
            borderColor: COLORS.Color206,
            width: '100%',
            borderBottomWidth: 1,
        },
        TxtSectionSignIn40: {
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(13),
            fontFamily: 'Muli',
            lineHeight: 15,
            color: COLORS.Color726,
        },
        LineSectionSignIn41: {
            borderColor: COLORS.Color206,
            width: '100%',
            borderBottomWidth: 1,
        },
        EleSectionSignIn42: {
            marginBottom: verticalScale(19),
        },
        ParagraphSectionSignIn43: {
            marginBottom: verticalScale(34),
            flexDirection: 'row',
        },
        TxtSectionSignIn44: {
            fontSize: verticalScale(14),
            fontFamily: 'Muli',
            lineHeight: 15,
            color: COLORS.Color718,
        },
        image45: {
            marginBottom: verticalScale(32),
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            width: scale(390),
            height: scale(530),
        },
        TxtSectionForgetPass46: {
            marginBottom: verticalScale(16),
            fontSize: verticalScale(22),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        TextsInput48: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color758,
        },
        InputRect49: {
            paddingRight: scale(161),
            paddingLeft: scale(12),
            borderWidth: 1,
            borderColor: COLORS.Color321,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Input47: {
            marginBottom: verticalScale(16),
            width: '100%',
            height: verticalScale(48),
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        TextsButton52: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color672,
        },
        ButtonRect51: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(13),
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button50: {
            marginBottom: verticalScale(23),
            width: '100%',
            height: verticalScale(51),
        },
        TxtSectionForgetPass53: {
            marginBottom: verticalScale(31),
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(14),
            fontFamily: 'Muli',
            lineHeight: 15,
            color: COLORS.Color718,
        },
        SectionPaddingquestion255: {
            paddingBottom: verticalScale(-2),
            paddingTop: verticalScale(-6),
            paddingRight: scale(120),
            paddingLeft: scale(120),
        },
        Txtquestion256: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        Image57: {
            width: scale(390),
            height: scale(84),
        },
        SectionPaddingquestion258: {
            paddingBottom: verticalScale(32),
            paddingTop: verticalScale(32),
            paddingRight: scale(32),
            paddingLeft: scale(32),
        },
        Txtquestion259: {
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 39,
            color: COLORS.Color209,
        },
        Txtquestion260: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        TextsCheckBox62: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox61: {
            flexDirection: 'row',
        },
        TextsCheckBox64: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox63: {
            flexDirection: 'row',
        },
        TextsCheckBox66: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox65: {
            flexDirection: 'row',
        },
        TextsCheckBox68: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox67: {
            flexDirection: 'row',
        },
        TextsCheckBox70: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox69: {
            flexDirection: 'row',
        },
        TextsCheckBox72: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox71: {
            flexDirection: 'row',
        },
        TextsCheckBox74: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox73: {
            flexDirection: 'row',
        },
        TextsCheckBox76: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox75: {
            flexDirection: 'row',
        },
        TextsCheckBox78: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color603,
        },
        CheckBox77: {
            flexDirection: 'row',
        },
        TextsButton81: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color963,
        },
        ButtonRect80: {
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
            alignSelf: 'center',
        },
        Button79: {
            width: '90%',
            height: verticalScale(52),
            alignSelf: 'center',
        },
        image82: {
            marginBottom: verticalScale(32),
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            width: scale(326),
            height: scale(417),
        },
        TxtSectionVerification83: {
            marginBottom: verticalScale(8),
            fontSize: verticalScale(22),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        TxtSectionVerification84: {
            marginBottom: verticalScale(14),
            fontSize: verticalScale(15),
            fontFamily: 'Muli',
            lineHeight: 16,
            color: COLORS.Color726,
        },
        InputRect86: {
            borderWidth: 1,
            borderColor: COLORS.Color321,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Input85: {
            marginBottom: verticalScale(10),
            width: '100%',
            height: verticalScale(48),
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        TxtSectionVerification87: {
            marginBottom: verticalScale(39),
            fontSize: verticalScale(15),
            fontFamily: 'Muli',
            lineHeight: 16,
            color: COLORS.Color525,
        },
        TextsButton90: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color672,
        },
        ButtonRect89: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(13),
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button88: {
            marginBottom: verticalScale(21),
            width: '100%',
            height: verticalScale(51),
        },
        TextsButton93: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color289,
        },
        ButtonRect92: {
            paddingBottom: verticalScale(11),
            paddingTop: verticalScale(10),
            paddingRight: 0,
            paddingLeft: 0,
            borderWidth: 2,
            borderColor: COLORS.Color289,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button91: {
            width: '100%',
            height: verticalScale(51),
        },
        image94: {
            marginBottom: verticalScale(78),
            width: scale(390),
            height: scale(494),
        },
        TxtSectionQuestion95: {
            marginBottom: verticalScale(16),
            fontSize: verticalScale(22),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        TxtSectionQuestion96: {
            marginBottom: verticalScale(19),
            fontSize: verticalScale(14),
            fontFamily: 'Muli',
            lineHeight: 26,
            color: COLORS.Color726,
        },
        TextsButton99: {
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color672,
        },
        ButtonRect98: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(13),
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button97: {
            width: '100%',
            height: verticalScale(51),
        },
        EleHiquestion2100: {
            marginBottom: verticalScale(32),
        },
        TxtSectionTop101: {
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            // lineHeight: 42,
            color: COLORS.Color209,
        },
        Image102: {
            marginBottom: verticalScale(36),
            width: scale(381),
            height: scale(82),
        },
        SectionPaddingquestion6103: {
            paddingBottom: verticalScale(0),
            paddingTop: verticalScale(0),
            paddingRight: scale(32),
            paddingLeft: scale(32),
            marginBottom: verticalScale(178),
        },
        Txtquestion6104: {
            marginBottom: verticalScale(36),
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 39,
            color: COLORS.Color209,
        },
        Txtquestion6105: {
            marginBottom: verticalScale(16),
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 39,
            color: COLORS.Color209,
        },
        TextsInput107: {
            fontSize: verticalScale(14),
            fontFamily: 'Muli',
            lineHeight: 36,
            color: COLORS.Color267,
        },
        InputRect108: {
            paddingRight: scale(160),
            paddingLeft: scale(15),
            borderWidth: 1,
            borderColor: COLORS.Color321,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Input106: {
            marginBottom: verticalScale(88),
            width: '100%',
            height: verticalScale(48),
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Txtquestion6109: {
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            lineHeight: 30,
            color: COLORS.Color209,
        },
        TextsButton112: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color672,
        },
        ButtonRect111: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(13),
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button110: {
            width: scale(146),
            height: verticalScale(51),
        },
        TextsButton115: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color209,
        },
        ButtonRect114: {
            paddingBottom: verticalScale(12),
            paddingTop: verticalScale(11),
            paddingRight: 0,
            paddingLeft: 0,
            borderWidth: 1,
            borderColor: COLORS.Color276,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 8,
            borderTopRightRadius: 8,
            borderBottomRightRadius: 8,
            borderBottomLeftRadius: 8,
        },
        Button113: {
            width: scale(148),
            height: verticalScale(51),
        },
        SectionPaddingquestion7117: {
            paddingBottom: verticalScale(-2),
            paddingTop: verticalScale(-6),
            justifyContent: 'center',
            alignItems: 'center',
        },
        Txtquestion7118: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        Image119: {
            width: scale(390),
            height: scale(84),
        },
        SectionPaddingquestion7120: {
            paddingBottom: verticalScale(0),
            paddingTop: verticalScale(0),
            paddingRight: scale(32),
            paddingLeft: scale(32),
        },
        Txtquestion7121: {
            marginBottom: verticalScale(46),
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 39,
            color: COLORS.Color209,
        },
        SectionPaddingquestion7122: {
            marginBottom: verticalScale(24),
        },
        Txtquestion7123: {
            marginBottom: verticalScale(16),
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 39,
            color: COLORS.Color209,
        },
        TextsInput125: {
            fontSize: verticalScale(14),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color267,
        },
        InputRect126: {
            paddingRight: scale(166),
            paddingLeft: scale(15),
            borderWidth: 1,
            borderColor: COLORS.Color321,
            backgroundColor: COLORS.Color963,
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Input124: {
            width: '100%',
            height: verticalScale(48),
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Txtquestion7127: {
            marginBottom: verticalScale(25),
            fontSize: verticalScale(17),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 39,
            color: COLORS.Color209,
        },
        TextsCheckBox129: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox128: {
            paddingBottom: verticalScale(13),
            paddingTop: verticalScale(11),
            paddingRight: scale(232),
            paddingLeft: scale(16),
            marginBottom: verticalScale(16),
            flexDirection: 'row',
        },
        TextsCheckBox131: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox130: {
            paddingBottom: verticalScale(13),
            paddingTop: verticalScale(11),
            paddingRight: scale(219),
            paddingLeft: scale(16),
            marginBottom: verticalScale(16),
            flexDirection: 'row',
        },
        TextsCheckBox133: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color886,
        },
        CheckBox132: {
            paddingBottom: verticalScale(13),
            paddingTop: verticalScale(11),
            paddingRight: scale(216),
            paddingLeft: scale(16),
            flexDirection: 'row',
        },
        image134: {
            marginBottom: verticalScale(22),
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            width: scale(390),
            height: scale(452.02),
        },
        TxtSectionVerify135: {
            marginBottom: verticalScale(16),
            fontSize: verticalScale(22),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        TextsButton138: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color672,
        },
        ButtonRect137: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(13),
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button136: {
            marginBottom: verticalScale(24),
            width: '100%',
            height: verticalScale(51),
        },
        TxtSectionVerify139: {
            marginBottom: verticalScale(26),
            fontSize: verticalScale(14),
            fontFamily: 'Muli',
            lineHeight: 26,
            color: COLORS.Color516,
        },
        SectionPaddingSectiontop1140: {
            paddingBottom: verticalScale(-2),
            paddingTop: verticalScale(-6),
            justifyContent: 'center',
            alignItems: 'center',
        },
        TxtSectiontop1141: {
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            lineHeight: 42,
            color: COLORS.Color209,
        },
        image142: {
            marginBottom: verticalScale(49),
            shadowColor: 'rgba(140,140,140,0.16)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 28,
            width: scale(390),
            height: scale(452.02),
        },
        TxtSectionStart143: {
            marginBottom: verticalScale(16),
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(26),
            fontFamily: 'Muli',
            fontWeight: 'bold',
            lineHeight: 24,
            color: COLORS.Color726,
        },
        TxtSectionStart144: {
            marginBottom: verticalScale(83),
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(15),
            fontFamily: 'Muli',
            lineHeight: 26,
            color: COLORS.Color726,
        },
        TextsButton147: {
            alignSelf: 'center',
            textAlign: 'center',
            fontSize: verticalScale(16),
            fontFamily: 'Muli',
            color: COLORS.Color672,
        },
        ButtonRect146: {
            paddingBottom: verticalScale(14),
            paddingTop: verticalScale(13),
            paddingRight: 0,
            paddingLeft: 0,
            shadowColor: 'rgba(39,97,236,0.12)',
            shadowOffset: { width: 0, height: 0 },
            shadowRadius: 18,
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            borderBottomRightRadius: 12,
            borderBottomLeftRadius: 12,
        },
        Button145: {
            width: '100%',
            height: verticalScale(51),
        },
        EleGettingstarted3148: {
            marginBottom: verticalScale(32),
        },
        image320: {
            marginTop: verticalScale(103),
            marginBottom: verticalScale(103),
            width: '100%',
            height: scale(175),
        },
        image221: {
            width: scale(390),
            // height: scale(144),
        },
        image1190: {
            marginBottom: verticalScale(103),
            width: scale(390),
            height: scale(130),
        },
    });
}
