export default function () {
    return {
        image2228: require('assets/images/image2228.png'),
        image7352: require('assets/images/image7352.png'),
        image6296: require('assets/images/image6296.png'),
        image2101: require('assets/images/image2101.png'),
        image1335: require('assets/images/image1335.png'),
        image3013: require('assets/images/image3013.png'),
        image2773: require('assets/images/image2773.png'),
        image6696: require('assets/images/image6696.png'),
        image4477: require('assets/images/image4477.png'),
        image2754: require('assets/images/image2754.png'),
        image7436: require('assets/images/image7436.png'),
        image5606: require('assets/images/image5606.png'),
        image9641: require('assets/images/image9641.png'),
        image2834: require('assets/images/image2834.png'),
        image6011: require('assets/images/image6011.png'),
        image6462: require('assets/images/image6462.png'),
        image7641: require('assets/images/image7641.png'),
        imageBack1: require('assets/images/imageBack1.png'),
        imageBack2: require('assets/images/imageBack2.png'),
        intro2: require('assets/images/intro-1.png'),
        intro3: require('assets/images/intro-2.png'),
        intro4: require('assets/images/intro-3.png'),
        image7104: require('assets/images/image7104.jpeg'),
        hiBack: require('assets/images/hiBack.png'),
        splash1: require('assets/images/1.png'),
        splash2: require('assets/images/2.png'),
        splash3: require('assets/images/3.png'),
        splash4: require('assets/images/4.png'),
        google: require('assets/images/google.png'),
        checkEmail: require('assets/images/checkEmail.png'),
        loading: require('assets/images/loading.png'),
    };
}
